baseurl = "https://www.thomasantony.com/"
title = "Random Thoughts of an Engineer"
author = "Thomas Antony"
canonifyurls = true
languagecode = "en"
theme = "onetwothree"

[params]
twitter = "thomasantony"
navigation = ["about.md"]
style = ""



# theme = "black-and-light"

# pygmentsstyle       = "bw"
# pygmentscodefences  = true

# [params]
#   sitename = "Black & Light"
#   disableWebFonts = false

# # Social links
# [[params.social]]
#     name = "Github"
#     icon = "fab fa-github fa-2x"
#     weight = 1
#     url = "https://github.com/thomasantony/"
# [[params.social]]
#     name = "Gitlab"
#     icon = "fab fa-gitlab fa-2x"
#     weight = 2
#     url = "https://gitlab.com/thomasantony/"
# [[params.social]]
#     name = "Twitter"
#     icon = "fab fa-twitter fa-2x"
#     weight = 3
#     url = "https://twitter.com/thomasantony/"

# # Menu links
# [[menu.main]]
#     name = "Blog"
#     weight = 1
#     url  = "/posts/"
# [[menu.main]]
#     name = "About"
#     weight = 2
#     url = "/about/"