baseurl = "https://www.thomasantony.com/"
title = "Thomas Antony's Website"
# author = "Thomas Antony"
canonifyurls = true
languagecode = "en"
googleAnalytics = "UA-56045487-1"
defaultContentLanguage = "en"

theme = "KeepIt"

[params]
author = "Thomas Antony"
subtitle = "A blog"
home_mode = "other" # post or other

google_verification = ""
bing_verification = ""
yandex_verification = ""
pinterest_verification = ""
baidu_verification = ""

avatar = "/images/me/avatar.jpeg"
socialShare = true

description = "" # site description
keywords = "" # site keywords

license= 'Released under <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

paginate = 12
enableEmoji = true
enableRobotsTXT = true

[params.social]
    GitHub = "thomasantony"
    Linkedin = "thomasantony"
    Twitter = "thomasantony"

[params.share]
Twitter = true
Facebook = true
Linkedin = true

 
[Permalinks]
    posts = "/:year/:filename/"

# Menu links
[[menu.main]]
    name = "Posts"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"

##############################
# theme = "LoveIt"
# [params]
#     # LoveIt theme version
#     version = "0.2.X"
#     dateFormat = "2006-01-02"
#     # Home page config
#     [params.home]
#         # LoveIt NEW | 0.2.0 amount of RSS pages
#         rss = 10
#     # Home page profile
#     [params.home.profile]
#         enable = true
#         # URL of avatar shown in home page
#         avatarURL = "/images/me/avatar.jpeg"
#         # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
#         title = ""
#         # subtitle shown in home page
#         subtitle = "Hi, I am Thomas. Welcome to my website"
#         # whether to use typeit animation for subtitle
#         typeit = true
#         # whether to show social links
#         social = true
#         # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
#         disclaimer = ""
#     # Home page posts
#     [params.home.posts]
#         enable = false
#         # special amount of posts in each home posts page
#         paginate = 6
#         # LoveIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
#         # default behavior when you don't set "hiddenFromHomePage" in front matter
#         defaultHiddenFromHomePage = false

#     # Social config about the author
#     [params.social]
#         GitHub = "thomasantony"
#         Linkedin = "thomasantony"
#         Twitter = "thomasantony"
#     [params.page.math]
#         enable = true

#     # LoveIt NEW | 0.2.0 Section (all posts) page config
#     [params.section]
#         # special amount of posts in each section page
#         paginate = 20
#         # date format (month and day)
#         dateFormat = "January 01, 2006"
#         # # amount of RSS pages
#         # rss = 10

# [author]
# name = "Thomas Antony"

# [menu]
#   [[menu.main]]
#     identifier = "posts"
#     # you can add extra information before the name (HTML format is supported), such as icons
#     pre = ""
#     # you can add extra information after the name (HTML format is supported), such as icons
#     post = ""
#     name = "Posts"
#     url = "/posts/"
#     # title will be shown when you hover on this menu link
#     title = ""
#     weight = 1
# #   [[menu.main]]
# #     identifier = "tags"
# #     pre = ""
# #     post = ""
# #     name = "Tags"
# #     url = "/tags/"
# #     title = ""
# #     weight = 2
#   [[menu.main]]
#     identifier = "about"
#     pre = ""
#     post = ""
#     name = "About"
#     url = "about/"
#     weight = 2


# # Markup related configuration in Hugo
# [markup]
#   # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
#   [markup.highlight]
#     # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
#     noClasses = false

###########################
    
# theme = "hugo-flex"
# [params]
# color = "CornFlowerBlue"
# width = "42rem"
# footer = "Created with Hugo."
# rss = "To subscribe to this RSS feed, copy its address and paste it into your favorite feed reader."
# summaries = true
# divider = "\\a0"
# schema = false
# opengraph = false
# twittercards = false
# math = true

#   [params.utterances]
#   issueterm = "pathname"
#   theme = "github-light"

#   [params.netlify]
#   honeypot = false
#   recaptcha = false

# [menu]
#   [[menu.nav]]
#   name = "About"
#   url = "about/"
#   weight = 1.0

#   [[menu.nav]]
#   name = "Posts"
#   url = "posts/"
#   weight = 2.0



###############################

# theme = "black-and-light"

# pygmentsstyle       = "bw"
# pygmentscodefences  = true

# [params]
#   sitename = "Black & Light"
#   disableWebFonts = false

# # Social links
# [[params.social]]
#     name = "Github"
#     icon = "fab fa-github fa-2x"
#     weight = 1
#     url = "https://github.com/thomasantony/"
# [[params.social]]
#     name = "Gitlab"
#     icon = "fab fa-gitlab fa-2x"
#     weight = 2
#     url = "https://gitlab.com/thomasantony/"
# [[params.social]]
#     name = "Twitter"
#     icon = "fab fa-twitter fa-2x"
#     weight = 3
#     url = "https://twitter.com/thomasantony/"
